### ISSUE TITLE
grub-mkconfig takes too long

### ISSUE THREAD

**Issue by negativeExponent** [xfusionalg/alg-gnome-pure#3]
os-prober should be removed to avoid the long wait at the end of the install process, if multibooting is indeed a feature of alg, then a workaround should be done to avoid that long wait.

**Comment by xfusionalg** [comment]
Hi,

Thanks for your message, I haven't noticed that long wait, I'm running a dual core with SSD and I tested the ISO on virtual box what's your computer specs?

If you need an ISO without os-prober, you can clone this repository, remove os-prober from the package file, open the folder in terminal, write sudo mkarchiso -v . and it will build an ISO in the out folder, it's a resource intensive process it may take an hour or so.

Best regards, xfusion.
